### ISSUE TITLE
How do I get the title of the Paper?

### ISSUE THREAD

**Issue by rommyarb** [kermitt2/grobid-client-python#6]
Screenshot:
[https://paste.pics/d72fd7940436d35aaff30fef85c99fd1](https://paste.pics/d72fd7940436d35aaff30fef85c99fd1)

I am able to retrieve the header text with `processHeaderDocument`
How can I get the title instead of header text (blue rectangle, see the screenshot img)?

Thank you!

**Comment by kermitt2** [comment]
Hello @rommyarb  !

I would need more details to help. can you share the resulting TEI? 
It seems that the abstract is extracted, but not the title, is it correct ?
Failing to extract the title happens, we're trying to improve that. If you share the pdf with us, I can tst it and tell you more on this point.

**Comment by rommyarb** [comment]
Thank you @kermitt2! The issue has been resolved. I use `processFulltextDocument` instead. Thank you! ❤️️
